# Generated by Django 3.1 on 2020-08-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HammerBarbecue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data do churrasco')),
                ('location', models.CharField(max_length=255, verbose_name='Nome do participante')),
                ('spent_drinks', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Valor gasto em bebidas')),
                ('spent_foods', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Valor gasto em comida')),
            ],
            options={
                'verbose_name': 'Churrasco da Hammer',
                'verbose_name_plural': 'Churrascos da Hammer',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do participante')),
                ('consumes_alcohol', models.BooleanField(verbose_name='Consome bebida alcoólica')),
                ('email', models.CharField(max_length=156, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do convidado')),
                ('presence', models.BooleanField(default=False, verbose_name='Presença no churrasco')),
                ('contribution', models.FloatField(default=20, verbose_name='Valor a contribuir')),
                ('barbecue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hammerbarbecue')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'convites',
            },
        ),
    ]
