# Generated by Django 3.1 on 2020-08-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hammerbarbecue_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='consumes_alcohol',
        ),
    ]
