# Generated by Django 3.1 on 2020-08-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200831_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='consumes_alcohol',
            field=models.BooleanField(default=True, verbose_name='Vai consumir alcool'),
        ),
    ]
